2019-02-21 15:48:27,198 INFO: Matcha startup [in /Users/philou/Documents/Code/42/matcha/app/__init__.py:43]
2019-02-21 15:49:00,431 INFO: Matcha startup [in /Users/philou/Documents/Code/42/matcha/app/__init__.py:43]
2019-02-21 15:49:31,585 INFO: Matcha startup [in /Users/philou/Documents/Code/42/matcha/app/__init__.py:43]
2019-02-21 16:36:46,480 INFO: Matcha startup [in /Users/philou/Documents/Code/42/matcha/app/__init__.py:43]
2019-02-21 16:36:58,790 ERROR: Exception on /upload/ [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/philou/Documents/Code/42/matcha/app/routes.py", line 109, in upload
    file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
  File "/usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/app/images/cartedesejour2.jpg'
2019-02-26 12:32:59,678 INFO: Matcha startup [in /Users/philou/Documents/Code/42/matcha/app/__init__.py:43]
